language: python
env:
  - VIRTUALENV_SEEDER=pip
python: "3.6"
before_install:
  - openssl aes-256-cbc -K $encrypted_1adc08e29f14_key -iv $encrypted_1adc08e29f14_iv -in auth.tar.enc -out auth.tar -d
  - tar xvf auth.tar
install:
  - pip uninstall -y six
  - pip install six>=1.13.0
  - python setup.py install
script: python setup.py test
sudo: false
